name: continuous-integration
on:
  push:
    branches-ignore: [ga-ignore-*]
  pull_request:
    branches-ignore: [ga-ignore-*]

# Setup the environment variables
# MIRROR_URL: The repository to push the refs to
env:
  MIRROR_URL: git@github.com:IchiiDev/ws-target.git

jobs:
  coding-style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
    # Fetch the repository content
      - name: Checkout GH repository
        uses: actions/checkout@master

    # Run the banana script
      - name: Run coding-style.sh
        run: check.sh $(pwd) $(pwd)

    # Return an error if the banana report file is not empty
      - name: Report banana result
        run: |
          NB_ERROR=$(cat coding-style-reports.log | wc -l)
          if [ $NB_ERROR -gt 0 ]; then
            ERROR=$(cat coding-style-reports.log)
            echo "::error title=$NB_ERROR errors found::$ERROR"
            exit 1
          fi
          exit 0

  compile:
    runs-on: ubuntu-latest
    steps:
    # Fetch the repository content
      - name: Checkout GH repository
        uses: actions/checkout@master

    # Fetch the banana script
      - name: Compile repository
        run: make

    # Check if the binary is present in the repository
      - name: Check binary presence
        run: |
          if [ ! -f ./swapupcase ]; then
            echo "::error file=swapupcase,title="Binary Error"::Binary not found"
            exit 1
          fi
          exit 0

  run-tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    needs: [compile, coding-style]
    steps:
    # Fetch the repository content
      - name: Checkout GH repository
        uses: actions/checkout@master

    # Compile unit tests
      - name: Compile unit tests
        run: make compile_tests

    # Run unit tests
      - name: Run unit tests
        run: ./unit_testing

    # Run Integration tests
      - name: Run integration tests
        run: ./integration_testing


  push_to_mirror:
    name: Pushing refs to mirror
    runs-on: ubuntu-latest
    needs: [run-tests]
    # Only run this job if the event is a push event and the branch is main
    if: github.event_name == 'push' && github.ref_name == 'refs/heads/correction'
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v3 # Use v3 to be able to fetch all the refs

        # We need to fetch all the refs to be able to push them to the mirror
        # This ensures that we do not only checkout the source file
        # But also every commits and git related stuff
        with:
          fetch-depth: 0

      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.MIRROR_SSH_KEY }}
